"""migrate id to uuid

Revision ID: 02251ae1c97b
Revises: 
Create Date: 2026-06-28 16:22:02.580026
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '02251ae1c97b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('company', sa.String(length=180), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=180), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('gstNumber', sa.String(length=32), nullable=True),
    sa.Column('contactPerson', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('wasteInterests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('totalOrdered', sa.Float(), nullable=False),
    sa.Column('totalCarbon', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyers')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_buyers_id'), 'buyers', ['id'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_buyers_verified'), 'buyers', ['verified'], unique=False, schema='nalco')
    op.create_table('profiles',
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('NALCO_ADMIN', 'BUYER', 'LOGISTICS', 'AUDITOR', name='role'), nullable=False),
    sa.Column('companyId', sa.String(length=36), nullable=True),
    sa.Column('passwordHash', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('refreshTokenHash', sa.String(length=128), nullable=True),
    sa.Column('refreshTokenExpiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_profiles_email'), 'profiles', ['email'], unique=True, schema='nalco')
    op.create_index(op.f('ix_nalco_profiles_id'), 'profiles', ['id'], unique=False, schema='nalco')
    op.create_table('routes',
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=180), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('highway', sa.String(length=120), nullable=False),
    sa.Column('freightRate', sa.Float(), nullable=False),
    sa.Column('estimatedTime', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_routes_destination'), 'routes', ['destination'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_routes_id'), 'routes', ['id'], unique=False, schema='nalco')
    op.create_table('waste_streams',
    sa.Column('type', sa.Enum('RED_MUD', 'FLY_ASH', 'SPENT_POT_LINING', 'ALUMINIUM_DROSS', 'CAUSTIC_LIQUOR', 'LIME_GRIT', name='waste_type'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('chemicalFormula', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('avgPricePerMT', sa.Float(), nullable=False),
    sa.Column('carbonFactor', sa.Float(), nullable=False),
    sa.Column('monthlyProd', sa.Integer(), nullable=False),
    sa.Column('applications', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('currentStock', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_streams')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_waste_streams_id'), 'waste_streams', ['id'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_waste_streams_type'), 'waste_streams', ['type'], unique=True, schema='nalco')
    op.create_table('batches',
    sa.Column('batchCode', sa.String(length=64), nullable=False),
    sa.Column('wasteStreamId', sa.Uuid(), nullable=False),
    sa.Column('tonnes', sa.Float(), nullable=False),
    sa.Column('moisture', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', name='batch_status'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('treatmentMethod', sa.String(length=255), nullable=False),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wasteStreamId'], ['nalco.waste_streams.id'], name=op.f('fk_batches_wasteStreamId_waste_streams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_batches_batchCode'), 'batches', ['batchCode'], unique=True, schema='nalco')
    op.create_index(op.f('ix_nalco_batches_id'), 'batches', ['id'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_batches_status'), 'batches', ['status'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_batches_wasteStreamId'), 'batches', ['wasteStreamId'], unique=False, schema='nalco')
    op.create_table('orders',
    sa.Column('orderNumber', sa.String(length=64), nullable=False),
    sa.Column('buyerId', sa.Uuid(), nullable=False),
    sa.Column('batchId', sa.Uuid(), nullable=False),
    sa.Column('tonnes', sa.Float(), nullable=False),
    sa.Column('pricePerMT', sa.Float(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.Column('freightCost', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('highway', sa.String(length=120), nullable=False),
    sa.Column('truckCount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('estimatedDelivery', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualDelivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batchId'], ['nalco.batches.id'], name=op.f('fk_orders_batchId_batches')),
    sa.ForeignKeyConstraint(['buyerId'], ['nalco.buyers.id'], name=op.f('fk_orders_buyerId_buyers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_orders_batchId'), 'orders', ['batchId'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_orders_buyerId'), 'orders', ['buyerId'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_orders_id'), 'orders', ['id'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_orders_orderNumber'), 'orders', ['orderNumber'], unique=True, schema='nalco')
    op.create_index(op.f('ix_nalco_orders_status'), 'orders', ['status'], unique=False, schema='nalco')
    op.create_table('sensor_readings',
    sa.Column('batchId', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=180), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['batchId'], ['nalco.batches.id'], name=op.f('fk_sensor_readings_batchId_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_readings')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_sensor_readings_batchId'), 'sensor_readings', ['batchId'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_sensor_readings_id'), 'sensor_readings', ['id'], unique=False, schema='nalco')
    op.create_index('ix_sensor_readings_batch_timestamp', 'sensor_readings', ['batchId', 'timestamp'], unique=False, schema='nalco')
    op.create_table('carbon_credits',
    sa.Column('orderId', sa.Uuid(), nullable=False),
    sa.Column('buyerId', sa.Uuid(), nullable=False),
    sa.Column('tCO2e', sa.Float(), nullable=False),
    sa.Column('methodology', sa.String(length=120), nullable=False),
    sa.Column('registry', sa.String(length=160), nullable=False),
    sa.Column('valueINR', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('certificateUrl', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyerId'], ['nalco.buyers.id'], name=op.f('fk_carbon_credits_buyerId_buyers')),
    sa.ForeignKeyConstraint(['orderId'], ['nalco.orders.id'], name=op.f('fk_carbon_credits_orderId_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carbon_credits')),
    schema='nalco'
    )
    op.create_index(op.f('ix_nalco_carbon_credits_buyerId'), 'carbon_credits', ['buyerId'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_carbon_credits_id'), 'carbon_credits', ['id'], unique=False, schema='nalco')
    op.create_index(op.f('ix_nalco_carbon_credits_orderId'), 'carbon_credits', ['orderId'], unique=True, schema='nalco')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nalco_carbon_credits_orderId'), table_name='carbon_credits', schema='nalco')
    op.drop_index(op.f('ix_nalco_carbon_credits_id'), table_name='carbon_credits', schema='nalco')
    op.drop_index(op.f('ix_nalco_carbon_credits_buyerId'), table_name='carbon_credits', schema='nalco')
    op.drop_table('carbon_credits', schema='nalco')
    op.drop_index('ix_sensor_readings_batch_timestamp', table_name='sensor_readings', schema='nalco')
    op.drop_index(op.f('ix_nalco_sensor_readings_id'), table_name='sensor_readings', schema='nalco')
    op.drop_index(op.f('ix_nalco_sensor_readings_batchId'), table_name='sensor_readings', schema='nalco')
    op.drop_table('sensor_readings', schema='nalco')
    op.drop_index(op.f('ix_nalco_orders_status'), table_name='orders', schema='nalco')
    op.drop_index(op.f('ix_nalco_orders_orderNumber'), table_name='orders', schema='nalco')
    op.drop_index(op.f('ix_nalco_orders_id'), table_name='orders', schema='nalco')
    op.drop_index(op.f('ix_nalco_orders_buyerId'), table_name='orders', schema='nalco')
    op.drop_index(op.f('ix_nalco_orders_batchId'), table_name='orders', schema='nalco')
    op.drop_table('orders', schema='nalco')
    op.drop_index(op.f('ix_nalco_batches_wasteStreamId'), table_name='batches', schema='nalco')
    op.drop_index(op.f('ix_nalco_batches_status'), table_name='batches', schema='nalco')
    op.drop_index(op.f('ix_nalco_batches_id'), table_name='batches', schema='nalco')
    op.drop_index(op.f('ix_nalco_batches_batchCode'), table_name='batches', schema='nalco')
    op.drop_table('batches', schema='nalco')
    op.drop_index(op.f('ix_nalco_waste_streams_type'), table_name='waste_streams', schema='nalco')
    op.drop_index(op.f('ix_nalco_waste_streams_id'), table_name='waste_streams', schema='nalco')
    op.drop_table('waste_streams', schema='nalco')
    op.drop_index(op.f('ix_nalco_routes_id'), table_name='routes', schema='nalco')
    op.drop_index(op.f('ix_nalco_routes_destination'), table_name='routes', schema='nalco')
    op.drop_table('routes', schema='nalco')
    op.drop_index(op.f('ix_nalco_profiles_id'), table_name='profiles', schema='nalco')
    op.drop_index(op.f('ix_nalco_profiles_email'), table_name='profiles', schema='nalco')
    op.drop_table('profiles', schema='nalco')
    op.drop_index(op.f('ix_nalco_buyers_verified'), table_name='buyers', schema='nalco')
    op.drop_index(op.f('ix_nalco_buyers_id'), table_name='buyers', schema='nalco')
    op.drop_table('buyers', schema='nalco')
    # ### end Alembic commands ###
